### ISSUE TITLE
lifetime issues in RPC responses

### ISSUE THREAD

**Issue by dwrensha** [jparyani/pycapnp#103]
I [observed](https://github.com/dwrensha/sandstorm-test-python/commit/828e2eb62788cf6eb59d41b2a78510bc95c63e12) some weird behavior when using pycapnp to call the Sandstorm API.

I've narrowed down the problem to the following testcase.

Consider the following client and server:

```capnp
# test.capnp
@0xf834be71da7d1c5b;

interface Foo {
  foo @0 () -> ();
}

struct Bar {
   foo @0 :Foo;
}

interface Baz {
   grault @0 () -> (bar: Bar);
}
```

```python
# test_client.py

import capnp
import test_capnp

def main(host):
    client = capnp.TwoPartyClient(host)
    baz = client.bootstrap().cast_as(test_capnp.Baz)

    bar = baz.grault().wait().bar

    # No problem if I put the response into its own variable:
    # response = baz.grault().wait()
    # bar = response.bar

    foo = bar.foo
    foo.foo().wait()

if __name__ == '__main__':
    main("127.0.0.1:4000")
```

```cpp
// test_server.c++

#include <kj/async-io.h>
#include <kj/io.h>
#include <capnp/rpc-twoparty.h>
#include <capnp/rpc.capnp.h>
#include "test.capnp.h"
#include <iostream>

class FooImpl: public Foo::Server {
  kj::Promise<void> foo(FooContext context) override {
    std::cout << "in foo()\n";
    return kj::READY_NOW;
  }
};

class BazImpl: public Baz::Server {
  kj::Promise<void> grault(GraultContext context) override {
    context.getResults().getBar().setFoo(kj::heap<FooImpl>());
    return kj::READY_NOW;
  }
};

struct AcceptedConnection {
  kj::Own<kj::AsyncIoStream> connection;
  capnp::TwoPartyVatNetwork network;
  capnp::RpcSystem<capnp::rpc::twoparty::VatId> rpcSystem;

  explicit AcceptedConnection(Baz::Client baz,
                              kj::Own<kj::AsyncIoStream>&& connectionParam)
    : connection(kj::mv(connectionParam)),
      network(*connection, capnp::rpc::twoparty::Side::SERVER),
      rpcSystem(capnp::makeRpcServer(network, baz)) {}
};

kj::Promise<void> acceptLoop(kj::ConnectionReceiver& serverPort,
                             Baz::Client baz,
                             kj::TaskSet& taskSet) {
  return serverPort.accept().then(
      [&, baz = kj::mv(baz)](kj::Own<kj::AsyncIoStream>&& connection) mutable {
    auto connectionState = kj::heap<AcceptedConnection>(baz, kj::mv(connection));
    auto promise = connectionState->network.onDisconnect();
    taskSet.add(promise.attach(kj::mv(connectionState)));
    return acceptLoop(serverPort, kj::mv(baz), taskSet);
  });
}

class ErrorHandlerImpl: public kj::TaskSet::ErrorHandler {
public:
  void taskFailed(kj::Exception&& exception) override {
    KJ_LOG(ERROR, "connection failed", exception);
  }
};

int main() {
  auto ioContext = kj::setupAsyncIo();
  ErrorHandlerImpl errorHandler;
  kj::TaskSet tasks(errorHandler);
  Baz::Client baz = kj::heap<BazImpl>();

  auto acceptTask = ioContext.provider->getNetwork()
      .parseAddress("127.0.0.1:4000", 0)
      .then([&, baz= kj::mv(baz)](kj::Own<kj::NetworkAddress>&& addr) mutable {
    auto serverPort = addr->listen();
    auto promise = acceptLoop(*serverPort, kj::mv(baz), tasks);
    return promise.attach(kj::mv(serverPort));
  });

  acceptTask.wait(ioContext.waitScope);
}
```

If I launch the server and then try to run the client, I get this error:

```
Traceback (most recent call last):
  File "test_client.py", line 21, in <module>
    main("127.0.0.1:4000")
  File "test_client.py", line 17, in main
    foo = bar.foo
  File "capnp/lib/capnp.pyx", line 1028, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:23390)
  File "capnp/lib/capnp.pyx", line 1026, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:23296)
  File "capnp/lib/capnp.pyx", line 1022, in capnp.lib.capnp._DynamicStructReader._get (capnp/lib/capnp.cpp:23163)
capnp.lib.capnp.KjException: capnp/layout.c++:2030: failed: Message contains invalid capability pointer.
stack: 0x7f45583efdd4 0x7f45583f539c 0x7f4558c39dd7 0x7f4558bee0b6 0x7f4560c55d09 0x7f4560c5aeab 0x7f4560c5c696 0x7f4560c5c73b 0x7f4560c789c4 0x7f4560c7ac05 0x7f4560c7bc83 0x7f4560c929d4 0x558ec9ea5be7 0x7f455fe79580 0x558ec9ea5c89
```

It looks like the problem is that the response to the `grault()` call is somehow not living long enough.  I would expect pycapnp to handle whatever refcounting is necessary to make this work. If I hold on to that response in a variable, then the client succeeds, as expected.

**Comment by jparyani** [comment]
Thanks for the report and the simple reproduction case! I tweaked it to only use python and added it to the test suite (see https://github.com/jparyani/pycapnp/blob/5ffe7eb2f6cf7539f03be715613359efbf053afb/test/test_response.py).

**Comment by dwrensha** [comment]
Yay! The new pycapnp behaves as expected in the sandsstorm-test-python app.

**Comment by little-dude** [comment]
@jparyani would you mind making a release for this fix, please? I'm hitting the same issue, and 5ffe7eb2f6cf7539f03be715613359efbf053afb solves it :)

**Comment by jparyani** [comment]
Done. Version 0.5.9 should be up on pypi.

**Comment by little-dude** [comment]
thank you very much!
