### ISSUE TITLE
big-endian printing of raw data fails

### ISSUE THREAD

**Issue by kormat** [jparyani/pycapnp#106]
First, here's a trivial schema:
```
@0xf8ab7f5d71490fa9;

struct S {
    d @0 :Data;
}
```
and a trivial python file:
```
#!/usr/bin/python3

import capnp
import bug_capnp

o = bug_capnp.S.new_message(d=b"\xFF")
print(o)
```

This works fine on little-endian platforms (tested on x86_64):
```
$ ./bug.py 
(d = "\xff")
```
but fails on big-endian platforms (tested on 32bit arm):
```
$ ./bug.py 
Traceback (most recent call last):
  File "./bug.py", line 7, in <module>
    print(o)
  File "capnp/lib/capnp.pyx", line 1400, in capnp.lib.capnp._DynamicStructBuilder.__str__ (capnp/lib/capnp.cpp:30286)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 6: invalid start byte
```

**Comment by kormat** [comment]
Printing binary data as utf8 seems like a bad approach, because utf8 has sequences of bytes which are invalid.

**Comment by kormat** [comment]
Ping?
