### ISSUE TITLE
Pip install capnp error

### ISSUE THREAD

**Issue by khaledkbadr** [jparyani/pycapnp#117]
I have an error while installing capnp

```
Collecting pycapnp
  Downloading pycapnp-0.5.9.tar.gz (455kB)
    100% |████████████████████████████████| 460kB 1.6MB/s 
Installing collected packages: pycapnp
  Running setup.py install for pycapnp ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xg2n91gd/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-brwz13lc-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
    Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/capnp
    copying capnp/version.py -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/__init__.py -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/_gen.py -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/c++.capnp -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/schema.capnp -> build/lib.linux-x86_64-3.5/capnp
    creating build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/non_circular.pxd -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/helpers.pxd -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/asyncHelper.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/fixMaybe.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/capabilityHelper.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/checkCompiler.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/rpcHelper.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/serialize.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    creating build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/capnp_cpp.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/schema_cpp.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/types.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    creating build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/capnp.pxd -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/pickle_helper.py -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/__init__.py -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/capnp.pyx -> build/lib.linux-x86_64-3.5/capnp/lib
    creating build/lib.linux-x86_64-3.5/capnp/templates
    copying capnp/templates/setup.py.tmpl -> build/lib.linux-x86_64-3.5/capnp/templates
    copying capnp/templates/module.pyx -> build/lib.linux-x86_64-3.5/capnp/templates
    running build_ext
    creating /tmp/tmpp725tdns/tmp
    cc -c /tmp/timer_createddji54_z.c -o /tmp/tmpp725tdns/tmp/timer_createddji54_z.o
    /tmp/timer_createddji54_z.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createddji54_z.c: In function ‘main’:
    /tmp/timer_createddji54_z.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    cc /tmp/tmpp725tdns/tmp/timer_createddji54_z.o -o /tmp/tmpp725tdns/a.out
    /tmp/tmpp725tdns/tmp/timer_createddji54_z.o: In function `main':
    timer_createddji54_z.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    creating tmp
    creating tmp/tmpp725tdns
    cc -c /tmp/tmpp725tdns/vers.cpp -o tmp/tmpp725tdns/vers.o --std=c++11
    /tmp/tmpp725tdns/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
    compilation terminated.
    *WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
    fetching https://capnproto.org/capnproto-c++-0.5.2.tar.gz into /tmp/pip-build-xg2n91gd/pycapnp/bundled
    g++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    make: *** [src/capnp/compiler/capnpc-c++.o] Error 4
    make: *** Waiting for unfinished jobs....
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xg2n91gd/pycapnp/setup.py", line 176, in <module>
        'Topic :: Communications'],
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-xg2n91gd/pycapnp/setup.py", line 120, in run
        build_libcapnp(bundle_dir, build_dir)
      File "/tmp/pip-build-xg2n91gd/pycapnp/buildutils/build.py", line 30, in build_libcapnp
        raise RuntimeError('Make failed')
    RuntimeError: Make failed
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xg2n91gd/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-brwz13lc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xg2n91gd/pycapnp/
root@vm-2760:/tmp# 
```

**Comment by jparyani** [comment]
Can you try running `pip install -v pycapnp` and including its output (or the last 100 lines or so if it's too long).

**Comment by zarvox** [comment]
The following line from the log makes me suspect out-of-memory conditions:

```
g++: internal compiler error: Killed (program cc1plus)
```

Might also help to confirm/deny that by looking in the syslog.

**Comment by khaledkbadr** [comment]
Right now it just hangs on fetching capnproto-c++
```
creating /tmp/tmprrpgv1vj/tmp
    cc -c /tmp/timer_createw2pdokaw.c -o /tmp/tmprrpgv1vj/tmp/timer_createw2pdokaw.o
    /tmp/timer_createw2pdokaw.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createw2pdokaw.c: In function ‘main’:
    /tmp/timer_createw2pdokaw.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    cc /tmp/tmprrpgv1vj/tmp/timer_createw2pdokaw.o -o /tmp/tmprrpgv1vj/a.out
    /tmp/tmprrpgv1vj/tmp/timer_createw2pdokaw.o: In function `main':
    timer_createw2pdokaw.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    creating tmp
    creating tmp/tmprrpgv1vj
    cc -c /tmp/tmprrpgv1vj/vers.cpp -o tmp/tmprrpgv1vj/vers.o --std=c++11
    /tmp/tmprrpgv1vj/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
    compilation terminated.
    *WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
    fetching https://capnproto.org/capnproto-c++-0.5.2.tar.gz into /tmp/pip-build-0jvnxu00/pycapnp/bundled
```

**Comment by jparyani** [comment]
You can try installing Cap'n Proto globally in your system first. Pycapnp will detect and use that installation if it can. See https://capnproto.org/install.html for instructions.

**Comment by khaledkbadr** [comment]
Found the problem when I capnp manually logs had `virtual memory exhausted: Cannot allocate memory` and it was `make: *** Waiting for unfinished jobs....`
That's why it was stuck since I was running it on vm with low memory actually
