### ISSUE TITLE
Hitting traversal limit of 2**63

### ISSUE THREAD

**Issue by plesner** [jparyani/pycapnp#137]
I've been seeing a problem where when I read a message, even if I set `traversal_limit_in_words` to 2**63, an `Exceeded message traversal limit` error is triggered almost immediately. This code demonstrates the problem,

### test.capnp
```text
@0xa9c85a8491f44b36;

struct Entry {
  f0 @0 :UInt64;
  f1 @1 :UInt64;
  f2 @2 :UInt64;
  f3 @3 :UInt64;
}

struct EntryCollection {
  entries @0: List(Entry);
}
```

### test.py
```python
#!/usr/bin/env python

import capnp
test_cnp = capnp.load("test.capnp")


def test():
  count = 1024
  builder = test_cnp.EntryCollection.new_message()
  entries = builder.init("entries", count)
  for i in range(0, count):
    entries[i].f0 = i
    entries[i].f1 = 10 + i
    entries[i].f2 = 20 + i
    entries[i].f3 = 30 + i

  message = test_cnp.EntryCollection.from_bytes(builder.to_bytes(),
    traversal_limit_in_words=2**63)
  for i in range(0, count):
    assert message.entries[i].f0 == i
    assert message.entries[i].f1 == 10 + i
    assert message.entries[i].f2 == 20 + i
    assert message.entries[i].f3 == 30 + i


if __name__ == "__main__":
  test()
```

This is what happens when I run `test.py`,

```shell
(venv) plesner@sirius:~/Workspace/temp$ pip list | grep pycapnp
pycapnp (0.5.10)
(venv) plesner@sirius:~/Workspace/temp$ time ./test.py 
Traceback (most recent call last):
  File "./test.py", line 27, in <module>
    test()
  File "./test.py", line 22, in test
    assert message.entries[i].f2 == 20 + i
  File "capnp/lib/capnp.pyx", line 1029, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:23461)
  File "capnp/lib/capnp.pyx", line 1027, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:23367)
  File "capnp/lib/capnp.pyx", line 1023, in capnp.lib.capnp._DynamicStructReader._get (capnp/lib/capnp.cpp:23237)
capnp.lib.capnp.KjException: src/capnp/arena.c++:106: failed: Exceeded message traversal limit.  See capnp::ReaderOptions.
stack: 0x7fdf0cfe6369 0x7fdf0cfea02d 0x7fdf0cf4a38c 0x7fdf0cfc6cd4 0x7fdf0cf8ee46 0x7fdf0cfb6a0c 0x7fdf0cfb740f 0x7fdf0ceab947 0x7fdf0ce3a6fc 0x55caae595d35 0x55caae598d59 0x55caae59adb9 0x55caae59aebf 0x55caae5c7a29 0x55caae5c7c65 0x55caae4b583f

real	0m0.109s
user	0m0.104s
sys	0m0.004s
```

The key seems to be in lines 20-23 where the code repeatedly accesses `message.entries[i]` because if you hoist `message.entries` out of the loop into a local variable there is no problem.

**Comment by asilversempirical** [comment]
I've run into a similar issue. I think there is a bug in `from_bytes`, or the type of reader it uses, such that it effectively ignores the `traversal_limit_in_words` argument. That's what I remember from trying to dig into this last time.

If it ignores the limit, you're stuck with the default of 64MB which would be easy to hit.

As a workaround, can you try to write that message to a file and then read it with
`message = test_cnp.EntryCollection.read(<file>, traversal_limit_in_words=2**63)` and see if the problem persists?

**Comment by plesner** [comment]
I'll give that a try and see if it has any effect.

It does puzzle me though that it makes a difference whether you do `.entries` on each iteration of the loop or just once. As far as I understand the traversal limit both should have the exact same effect.

**Comment by kentonv** [comment]
Each time you evaluate `message.entries`, you are traversing the `.entries` pointer. There isn't any bookkeeping to remember if you've followed it before (that would be too expensive), so each time you follow it, it is counted against the traversal limit again. It's a pretty crappy check but I couldn't think of any better way to solve the message size amplification security issues without hurting performance.

Note that each time you traverse `.entries`, you incur FFI overhead (calling C++ code from Python) and pointer validation overhead, so lifting it out of the loop is a good idea for performance anyway.

All that said, it does seem like there's a bug here, because even as-written you shouldn't be getting anywhere near 2^63 words traversed.

**Comment by pvernaza** [comment]
I think this is a duplicate of https://github.com/jparyani/pycapnp/issues/116

**Comment by plesner** [comment]
Yep looks like the same thing. Hopefully someone will land the fix so both issues can be closed.
