### ISSUE TITLE
pip install pycapnp fails

### ISSUE THREAD

**Issue by stuaxo** [jparyani/pycapnp#56]
I guess I'm missing some library ??

```
pip install pycapnp
Downloading/unpacking pycapnp
  Downloading pycapnp-0.5.3.tar.gz (419kB): 419kB downloaded
  Running setup.py (path:/mnt/data/home/stu/.virtualenvs/tmp88/build/pycapnp/setup.py) egg_info for package pycapnp
    
Installing collected packages: pycapnp
  Running setup.py install for pycapnp
    cc -c /tmp/timer_createtv_2vJ.c -o /tmp/tmprhOqgf/tmp/timer_createtv_2vJ.o
    cc /tmp/tmprhOqgf/tmp/timer_createtv_2vJ.o -o /tmp/tmprhOqgf/a.out
    /tmp/tmprhOqgf/tmp/timer_createtv_2vJ.o: In function `main':
    timer_createtv_2vJ.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    cc -c /tmp/tmprhOqgf/vers.cpp -o tmp/tmprhOqgf/vers.o --std=c++11
    cc tmp/tmprhOqgf/vers.o -lrt -o /tmp/tmprhOqgf/vers
    building 'capnp.lib.capnp' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/include/python2.7 -c capnp/lib/capnp.cpp -o build/temp.linux-x86_64-2.7/capnp/lib/capnp.o --std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    capnp/lib/capnp.cpp:261:21: fatal error: kj/time.h: No such file or directory
     #include "kj/time.h"
                         ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /mnt/data/home/stu/.virtualenvs/tmp88/bin/python -c "import setuptools, tokenize;__file__='/mnt/data/home/stu/.virtualenvs/tmp88/build/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LzWOGO-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/data/home/stu/.virtualenvs/tmp88/include/site/python2.7:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/capnp

copying capnp/_gen.py -> build/lib.linux-x86_64-2.7/capnp

copying capnp/version.py -> build/lib.linux-x86_64-2.7/capnp

copying capnp/__init__.py -> build/lib.linux-x86_64-2.7/capnp

copying capnp/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp

copying capnp/schema.capnp -> build/lib.linux-x86_64-2.7/capnp

copying capnp/c++.capnp -> build/lib.linux-x86_64-2.7/capnp

creating build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/helpers.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/non_circular.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/checkCompiler.h -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/capabilityHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/asyncHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/rpcHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/fixMaybe.h -> build/lib.linux-x86_64-2.7/capnp/helpers

copying capnp/helpers/serialize.h -> build/lib.linux-x86_64-2.7/capnp/helpers

creating build/lib.linux-x86_64-2.7/capnp/includes

copying capnp/includes/types.pxd -> build/lib.linux-x86_64-2.7/capnp/includes

copying capnp/includes/capnp_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes

copying capnp/includes/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/includes

copying capnp/includes/schema_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes

creating build/lib.linux-x86_64-2.7/capnp/lib

copying capnp/lib/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/lib

copying capnp/lib/capnp.pxd -> build/lib.linux-x86_64-2.7/capnp/lib

copying capnp/lib/__init__.py -> build/lib.linux-x86_64-2.7/capnp/lib

copying capnp/lib/pickle_helper.py -> build/lib.linux-x86_64-2.7/capnp/lib

copying capnp/lib/capnp.pyx -> build/lib.linux-x86_64-2.7/capnp/lib

creating build/lib.linux-x86_64-2.7/capnp/templates

copying capnp/templates/setup.py.tmpl -> build/lib.linux-x86_64-2.7/capnp/templates

copying capnp/templates/module.pyx -> build/lib.linux-x86_64-2.7/capnp/templates

running build_ext

creating /tmp/tmprhOqgf/tmp

cc -c /tmp/timer_createtv_2vJ.c -o /tmp/tmprhOqgf/tmp/timer_createtv_2vJ.o

cc /tmp/tmprhOqgf/tmp/timer_createtv_2vJ.o -o /tmp/tmprhOqgf/a.out

/tmp/tmprhOqgf/tmp/timer_createtv_2vJ.o: In function `main':

timer_createtv_2vJ.c:(.text+0x15): undefined reference to `timer_create'

collect2: error: ld returned 1 exit status

creating tmp

creating tmp/tmprhOqgf

cc -c /tmp/tmprhOqgf/vers.cpp -o tmp/tmprhOqgf/vers.o --std=c++11

cc tmp/tmprhOqgf/vers.o -lrt -o /tmp/tmprhOqgf/vers

building 'capnp.lib.capnp' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/capnp

creating build/temp.linux-x86_64-2.7/capnp/lib

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/include/python2.7 -c capnp/lib/capnp.cpp -o build/temp.linux-x86_64-2.7/capnp/lib/capnp.o --std=c++11

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

capnp/lib/capnp.cpp:261:21: fatal error: kj/time.h: No such file or directory

 #include "kj/time.h"

                     ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /mnt/data/home/stu/.virtualenvs/tmp88/bin/python -c "import setuptools, tokenize;__file__='/mnt/data/home/stu/.virtualenvs/tmp88/build/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LzWOGO-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/data/home/stu/.virtualenvs/tmp88/include/site/python2.7 failed with error code 1 in /mnt/data/home/stu/.virtualenvs/tmp88/build/pycapnp
Traceback (most recent call last):
  File "/mnt/data/home/stu/.virtualenvs/tmp88/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/mnt/data/home/stu/.virtualenvs/tmp88/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/mnt/data/home/stu/.virtualenvs/tmp88/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

**Comment by jparyani** [comment]
Do you have a globally installed C++ libcapnp? If so, my guess is it's out of date. Either you can update it, or you can use `pip install --install-option '--force-bundled-libcapnp' pycapnp`. If not, try the pip command anyways and let me know if it has the same problem.

**Comment by stuaxo** [comment]
Awesome, this worked !     I was able to use the calculator example ... are there any examples about using pycapn over MMAP ?

I'm thinking this would be great for a graphics API where the rendering is in a seperate process...  most calls wouldn't return anything, but occasionally they will return something large.

e.g.

```
def moveto(x, y):
    # go to x, y
def rectangle(w,h):
    # draw rectangle, width, height
def circle(d):
    # draw circle diameter d
def snapshot():
    # return bitmap of current scene
```

I do have it installed a global libcapnp installed, I guess that was causing the problem.

**Comment by jparyani** [comment]
Unfortunately, full RPC over MMAP isn't yet supported. It's coming soon (see https://capnproto.org/roadmap.html), but we'll have to wait until it's supported in the upstream C++ library.
