### ISSUE TITLE
error when running thread example

### ISSUE THREAD

**Issue by brennerm** [jparyani/pycapnp#61]
I'm getting the following error, when trying to run the thread example:
```bash
$  python3 thread_client.py 127.0.0.1:12345
main: 1428516848.193406
Traceback (most recent call last):
  File "thread_client.py", line 58, in <module>
    main(parse_args().host)
  File "thread_client.py", line 50, in main
    cap.longRunning().wait()
  File "capnp/lib/capnp.pyx", line 1854, in capnp.lib.capnp._RemotePromise.wait (capnp/lib/capnp.cpp:39409)
capnp.lib.capnp.KjException: (remote):0: failed: remote exception: This vat does not expose any public/bootstrap interfaces.
stack: 0x101752666 0x1016cf26c 0x1016ca27f 0x10173b1e7 0x1017534ce 0x101738404 0x1017385a0 0x1016c9c28 0x10173b1e7 0x1017534ce 0x101738404 0x10173c536 0x101736fec 0x1016523f0 0x1015a5284 0x1015e4b77
```

Am I missing something?
Running on MacOSX 10.10.2.

**Comment by brennerm** [comment]
On my linux machine I'm getting a different error:
```bash
$ python3 thread_client.py localhost:12345                                                                                                                    :(
main: 1428518629.8434916
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "thread_client.py", line 38, in start_status_thread
    promise.wait()
  File "capnp/lib/capnp.pyx", line 1854, in capnp.lib.capnp._RemotePromise.wait (capnp/lib/capnp.cpp:39409)
capnp.lib.capnp.KjException: src/kj/async-io.c++:211: disconnected: ::read(fd, buffer, maxBytes): Connection reset by peer
stack: 0x7fcb3b23a579 0x7fcb3b1bf8dd 0x7fcb3b226b48 0x7fcb3b221e27 0x7fcb3b225b18 0x7fcb3b158496 0x7fcb3b11f5a3 0x7fcb3b11f6b4 0x7fcb3b11fbdb 0x57c278 0x57d3d3 0x57e0eb 0x43810a 0x579616 0x57c0db 0x57c0db

Traceback (most recent call last):
  File "thread_client.py", line 58, in <module>
    main(parse_args().host)
  File "thread_client.py", line 50, in main
    cap.longRunning().wait()
  File "capnp/lib/capnp.pyx", line 1854, in capnp.lib.capnp._RemotePromise.wait (capnp/lib/capnp.cpp:39409)
capnp.lib.capnp.KjException: src/kj/async-io.c++:211: disconnected: ::read(fd, buffer, maxBytes): Connection reset by peer
stack: 0x7fcb3b23a579 0x7fcb3b1bf8dd 0x7fcb3b226b48 0x7fcb3b221e27 0x7fcb3b225b18 0x7fcb3b158496 0x7fcb3b11f5a3 0x7fcb3b11f6b4 0x7fcb3b11fbdb 0x57c278 0x57c0db 0x57d3d3 0x60ba83 0x60bc85 0x60d3ac 0x41ec0d
```

**Comment by jparyani** [comment]
I'm able to reproduce, and it seems the calculator example is broken as well. I think it's related to changes I made in 6e94182a3ed2ad367b370dbb852ecf8142770b0b, but I'm looking into it more.

**Comment by brennerm** [comment]
Thanks for your fast response. Let me know, if I can help in any way.

**Comment by jparyani** [comment]
Sorry it took so long to get to, I was a bit busier over the weekend than I planned. Let me know if this commit fixes it for you. If so, I'll push out a release shortly.

**Comment by brennerm** [comment]
When trying to install from source on MacOSX with this command:
```bash
$ pip install --install-option '--force-cython' ./pycapnp
```
I'm getting this error:
```bash
Processing ./pycapnp
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef _init(self, capnp.DynamicEnum other, object parent):
            self.thisptr = other
            self._parent = parent
            return self

        cpdef _as_str(self) except +reraise_kj_exception:
             ^
    ------------------------------------------------------------

    capnp/lib/capnp.pyx:877:10: Signature not compatible with previous declaration

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef class _DynamicEnum:
        cdef capnp.DynamicEnum thisptr
        cdef public object _parent

        cdef _init(self, capnp.DynamicEnum other, object parent)
        cpdef _as_str(self)
                     ^
    ------------------------------------------------------------

    capnp/lib/capnp.pxd:105:18: Previous declaration is here

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            """
            self._check_write()
            _write_packed_message_to_fd(file.fileno(), self._parent)
            self._is_written = True

        cpdef to_bytes(_DynamicStructBuilder self) except +reraise_kj_exception:
             ^
    ------------------------------------------------------------

    capnp/lib/capnp.pyx:1143:10: Signature not compatible with previous declaration

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef object _schema

        cdef _init(self, DynamicStruct_Builder other, object parent, bint isRoot=?, bint tryRegistry=?)

        cdef _check_write(self)
        cpdef to_bytes(_DynamicStructBuilder self)
                      ^
    ------------------------------------------------------------

    capnp/lib/capnp.pxd:55:19: Previous declaration is here

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            cdef const char* ptr = <const char *>array.begin()
            cdef bytes ret = ptr[:8*array.size()]
            self._is_written = True
            return ret

        cpdef _to_bytes_packed_helper(_DynamicStructBuilder self, word_count) except +reraise_kj_exception:
             ^
    ------------------------------------------------------------

    capnp/lib/capnp.pyx:1160:10: Signature not compatible with previous declaration

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        cdef _init(self, DynamicStruct_Builder other, object parent, bint isRoot=?, bint tryRegistry=?)

        cdef _check_write(self)
        cpdef to_bytes(_DynamicStructBuilder self)
        cpdef _to_bytes_packed_helper(_DynamicStructBuilder self, word_count)
                                     ^
    ------------------------------------------------------------

    capnp/lib/capnp.pxd:56:34: Previous declaration is here

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            array = helpers.messageToPackedBytes(deref(builder.thisptr), word_count)
            cdef const char* ptr = <const char *>array.begin()
            cdef bytes ret = ptr[:array.size()]
            return ret

        cpdef to_bytes_packed(_DynamicStructBuilder self) except +reraise_kj_exception:
             ^
    ------------------------------------------------------------

    capnp/lib/capnp.pyx:1167:10: Signature not compatible with previous declaration

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef _init(self, DynamicStruct_Builder other, object parent, bint isRoot=?, bint tryRegistry=?)

        cdef _check_write(self)
        cpdef to_bytes(_DynamicStructBuilder self)
        cpdef _to_bytes_packed_helper(_DynamicStructBuilder self, word_count)
        cpdef to_bytes_packed(_DynamicStructBuilder self)
                             ^
    ------------------------------------------------------------

    capnp/lib/capnp.pxd:57:26: Previous declaration is here
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/1r/540qmj1j7pbcw7jxj3tglf140000gn/T/pip-u_9ysitg-build/setup.py", line 122, in <module>
        extensions = cythonize('capnp/lib/*.pyx')
      File "/usr/local/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
        cythonize_one(*args[1:])
      File "/usr/local/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: capnp/lib/capnp.pyx
    missing cimport in module 'schema_cpp': ./capnp/includes/capnp_cpp.pxd
    missing cimport in module 'capnp_cpp': ./capnp/includes/schema_cpp.pxd
    missing cimport in module 'non_circular': ./capnp/helpers/helpers.pxd
    Compiling capnp/lib/capnp.pyx because it changed.
    Cythonizing capnp/lib/capnp.pyx

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/1r/540qmj1j7pbcw7jxj3tglf140000gn/T/pip-u_9ysitg-build
```

Please assist with installing, to confirm that the bug is fixed.

**Comment by jparyani** [comment]
It's a bug in Cython that will get sorted out whenever they push a new release. For now, you have to downgrade cython like so: `pip install cython==0.21.2`

**Comment by brennerm** [comment]
Alright, everything works now. Thanks for your support :)
